### PR TITLE
add backend server to todoapp

### PR DESCRIPTION
**Pull request by HimansuWebCoder**
I successfully add backend server to todo app. but just got frustrated to frontend confused so much even spent hours of hours fix this frontend by see backend routes ok.

### CODE REVIEW

**Comment by HimansuWebCoder** [comment]
I have submitted this pull request, but please note that there are failing checks. It would be great if you could take a look and fix these issues after the merge.

**Comment by prashantkumarpro** [comment]
I accepted

**Comment by HimansuWebCoder** [comment]
Great 👍 fix the Frontend according to you.

**Comment by HimansuWebCoder** [comment]
Any bug 🐛 or issue if you find inform me.

**Pull request closed without merging**
